default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  postgres
  password: ridwan

development:
  <<: *default
  database: Recipe_App_development

test:
  <<: *default
  database: Recipe_App_test

production:
  <<: *default
  database: Recipe_App_production
  username: Recipe_App
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
